SET SCHEMA VIDEOBASE;

CREATE TABLE VIDEOS (
    VIDEO_ID INT NOT NULL,
    TITLE VARCHAR(128) NOT NULL,
    LENGTH INT,
    USER_ID INT,
    CAM_MANUFACTURER VARCHAR(16),
    CAM_MODEL VARCHAR(32)
    );

CREATE TABLE CAMERAS (
    MANUFACTURER VARCHAR(16) NOT NULL,
    MODEL VARCHAR(32) NOT NULL
    );

CREATE TABLE USERS (
    USER_ID INT NOT NULL,
    USERNAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL
    );

CREATE TABLE SUBSCRIBERS (
    SUBSCRIBER_ID INT NOT NULL,
    SUBSCRIBED_TO_ID INT NOT NULL
);

CREATE TABLE DELETED (
    USER_ID CHAR(10) NOT NULL,
    REASON VARCHAR(32),
    DATE_DELETED TIMESTAMP
);

ALTER TABLE VIDEOS ADD PRIMARY KEY (VIDEO_ID);
ALTER TABLE CAMERAS ADD PRIMARY KEY (MANUFACTURER,MODEL);
ALTER TABLE USERS ADD PRIMARY KEY (USER_ID);
ALTER TABLE SUBSCRIBERS ADD PRIMARY KEY (SUBSCRIBER_ID,SUBSCRIBED_TO_ID);
ALTER TABLE DELETED ADD PRIMARY KEY (USER_ID);

ALTER TABLE VIDEOS ADD FOREIGN KEY (CAM_MANUFACTURER,CAM_MODEL)
    REFERENCES CAMERAS(MANUFACTURER,MODEL)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;

ALTER TABLE VIDEOS ADD FOREIGN KEY (USER_ID)
    REFERENCES USERS(USER_ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT;

ALTER TABLE SUBSCRIBERS ADD FOREIGN KEY (SUBSCRIBER_ID)
    REFERENCES USERS(USER_ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT;

ALTER TABLE SUBSCRIBERS ADD FOREIGN KEY (SUBSCRIBED_TO_ID)
    REFERENCES USERS(USER_ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT;

ALTER TABLE VIDEOS ADD CONSTRAINT CK_LEN
    CHECK (LENGTH > 0);
ALTER TABLE VIDEOS ADD CONSTRAINT CK_TITLE
    CHECK (TITLE != '');
ALTER TABLE USERS ADD CONSTRAINT CK_PASS
    CHECK (LENGTH(PASSWORD) >= 8);
ALTER TABLE USERS ADD CONSTRAINT CK_USERNAME
    CHECK (USERNAME NOT LIKE '% %');
ALTER TABLE SUBSCRIBERS ADD CONSTRAINT CK_SUB
    CHECK (SUBSCRIBER_ID != SUBSCRIBED_TO_ID);

CREATE SEQUENCE S_USER
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

CREATE SEQUENCE S_VIDEO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;