SET SCHEMA VIDEOBASE;
CREATE FUNCTION F_USERNAME(P_USER_ID INT)
RETURNS VARCHAR(32)
RETURN
    SELECT USERNAME FROM USERS
    WHERE USER_ID = P_USER_ID;

CREATE FUNCTION F_USER_SUBSCRIPTIONS(P_USER_ID INT)
RETURNS TABLE (
    ID INT,
    CHANNELS VARCHAR(32)
    )
RETURN
    SELECT SUBSCRIBED_TO_ID, VIDEOBASE.F_USERNAME(SUBSCRIBED_TO_ID)
    FROM SUBSCRIBERS
    WHERE SUBSCRIBER_ID = P_USER_ID;

CREATE FUNCTION F_USER_VIDEOS(P_USER_ID INT)
RETURNS TABLE (
    VIDEO_ID INT,
    TITLE VARCHAR(128),
    LENGTH INT,
    CAM_MANUFACTURER VARCHAR(16),
    CAM_MODEL VARCHAR(32)
    )
RETURN
    SELECT VIDEO_ID, TITLE, LENGTH, CAM_MANUFACTURER, CAM_MODEL
    FROM VIDEOS WHERE USER_ID = P_USER_ID;

CREATE FUNCTION F_USER_STATS(P_USER_ID INT)
RETURNS TABLE (
    USER_ID INT,
    USERNAME VARCHAR(32),
    VIDEO_COUNT INT,
    AVERAGE_TIME INT,
    SUBSCRIPTIONS INT,
    SUBSCRIBERS INT
    )
RETURN
    SELECT * FROM V_USER_STATS WHERE USER_ID = P_USER_ID;