SET SCHEMA VIDEOBASE;

CREATE TRIGGER T_AFTER_DEL_USER
    AFTER DELETE ON USERS
    REFERENCING OLD AS O
    FOR EACH ROW
        INSERT INTO DELETED(USER_ID, REASON, DATE_DELETED)
        VALUES (O.USER_ID,'Deleted',CURRENT_TIMESTAMP);

CREATE TRIGGER T_INSTEAD_INS_V_VIDEOS
    INSTEAD OF INSERT ON V_VIDEOS
    REFERENCING NEW AS N
    FOR EACH ROW
    BEGIN
        IF(MANUFACTURER IS NOT NULL AND MODEL IS NOT NULL
               AND NOT (EXISTS(SELECT C.MANUFACTURER, C.MODEL FROM CAMERAS AS C WHERE C.MANUFACTURER = N.MANUFACTURER AND C.MODEL = N.MODEL)
            ))
        THEN
            INSERT INTO CAMERAS VALUES (N.MANUFACTURER, N.MODEL);
        END IF;
        INSERT INTO VIDEOS VALUES (N.VIDEO_ID, N.TITLE, N.LENGTH, N.USER_ID, N.MANUFACTURER, N.MODEL);
    END;